name: 'WIP Gitflow'
description: 'WIP Gitflow'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  gh-token:
    description: 'GITHUB_TOKEN'
    required: true
  label:
    description: 'Test label to add to PR'
    required: true

branding:
  icon: 'git-pull-request'
  color: 'blue'